name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add clippy
        uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          default: true
          components: clippy
      - run: cargo clippy --all-features --all-targets -- -D warnings

  fmt:
    name: Fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add rustfmt
        uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          default: true
          components: rustfmt
      - run: |
          cargo fmt -- --check

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cargo build --all-features --all-targets --verbose

  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          cargo test --all-features --all-targets --verbose

  examples:
    name: Run examples
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          cargo run --example floating-precision
          cargo run --example simple-math
